CREATE TABLE DATA (
  unique_id varchar(100) NOT NULL,
  OFFICE varchar(30) NOT NULL,
  FISCAL_YEAR int NOT NULL,
  MONTH varchar(30) NOT NULL,
  SURVEY_GROUP int NOT NULL,
  SOLD_TO int NOT NULL,
  SOLD_TO_NAME text NOT NULL,
  GLOBAL_CUSTOMER text NOT NULL,
  FIRST_NAME text NOT NULL,
  LAST_NAME text NOT NULL,
  EMAIL varchar(100) NOT NULL,
  OVERALL_SATISFACTION text DEFAULT NULL,
  CUSTOMER_SERVICE_REPRESENTATIVE_SATISFACTION text DEFAULT NULL,
  EASE_OF_DOING_BUSINESS varchar(50) DEFAULT NULL,
  ADDITIONNAL_COMMENTS text DEFAULT NULL,
  CUSTOMER_SATISFACTION_INDEX int DEFAULT NULL
);

ALTER TABLE DATA
  ADD PRIMARY KEY (unique_id);

COMMIT;



