CREATE TABLE USERS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  FIRST_NAME varchar(50) NOT NULL,
  LAST_NAME varchar(50) NOT NULL,
  ROLE varchar(50) NOT NULL,
  EMAIL varchar(100) NOT NULL,
  PASSWORD varchar(512) NOT NULL,
  PRIVILEGES text NOT NULL,
);


COMMIT;